### ISSUE TITLE
Support on Xamarin Forms Android , IOS and UWP

### ISSUE THREAD

**Issue by amasasi** [VirgilSecurity/virgil-sdk-net#12]
Hello
I am trying to install Virgil.SDK on xamarin forms but I get this message

but when I install the Virgil.SDK 3.0.1 it succeeds

Attempting to gather dependency information for package 'Virgil.SDK.4.3.0' with respect to project 'MobileApp\MobileDataKit_Collect.Android', targeting 'MonoAndroid,Version=v6.0'
Gathering dependency information took 14.83 sec
Attempting to resolve dependencies for package 'Virgil.SDK.4.3.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Virgil.SDK.4.3.0'
Resolved actions to install package 'Virgil.SDK.4.3.0'
Retrieving package 'Newtonsoft.Json 7.0.1' from 'nuget.org'.
Retrieving package 'Virgil.Crypto 2.1.2' from 'nuget.org'.
Retrieving package 'Virgil.SDK 4.3.0' from 'nuget.org'.
Retrieving package 'Virgil.SDK.Contracts 1.1.2' from 'nuget.org'.
Adding package 'Newtonsoft.Json.7.0.1' to folder 'C:\Projects\DataKit\MobileDataKit\packages'
Added package 'Newtonsoft.Json.7.0.1' to folder 'C:\Projects\DataKit\MobileDataKit\packages'
Added package 'Newtonsoft.Json.7.0.1' to 'packages.config'
Executing script file 'C:\Projects\DataKit\MobileDataKit\packages\Newtonsoft.Json.7.0.1\tools\install.ps1'...
Successfully installed 'Newtonsoft.Json 7.0.1' to MobileDataKit_Collect.Android
Adding package 'Virgil.Crypto.2.1.2' to folder 'C:\Projects\DataKit\MobileDataKit\packages'
Added package 'Virgil.Crypto.2.1.2' to folder 'C:\Projects\DataKit\MobileDataKit\packages'
Added package 'Virgil.Crypto.2.1.2' to 'packages.config'
Successfully installed 'Virgil.Crypto 2.1.2' to MobileDataKit_Collect.Android
Adding package 'Virgil.SDK.Contracts.1.1.2' to folder 'C:\Projects\DataKit\MobileDataKit\packages'
Added package 'Virgil.SDK.Contracts.1.1.2' to folder 'C:\Projects\DataKit\MobileDataKit\packages'
Added package 'Virgil.SDK.Contracts.1.1.2' to 'packages.config'
Successfully installed 'Virgil.SDK.Contracts 1.1.2' to MobileDataKit_Collect.Android
Install failed. Rolling back...
Package 'Virgil.SDK.4.3.0 : Newtonsoft.Json [7.0.1, ), Virgil.Crypto [2.1.2, ), Virgil.SDK.Contracts [1.1.2, )' does not exist in project 'MobileDataKit_Collect.Android'
Removed package 'Virgil.SDK.Contracts.1.1.2' from 'packages.config'
Removed package 'Virgil.Crypto.2.1.2' from 'packages.config'
Removed package 'Newtonsoft.Json.7.0.1' from 'packages.config'
Removing package 'Virgil.SDK.Contracts.1.1.2' from folder 'C:\Projects\DataKit\MobileDataKit\packages'
Removed package 'Virgil.SDK.Contracts.1.1.2' from folder 'C:\Projects\DataKit\MobileDataKit\packages'
Removing package 'Virgil.Crypto.2.1.2' from folder 'C:\Projects\DataKit\MobileDataKit\packages'
Removed package 'Virgil.Crypto.2.1.2' from folder 'C:\Projects\DataKit\MobileDataKit\packages'
Removing package 'Newtonsoft.Json.7.0.1' from folder 'C:\Projects\DataKit\MobileDataKit\packages'
Removed package 'Newtonsoft.Json.7.0.1' from folder 'C:\Projects\DataKit\MobileDataKit\packages'
Executing nuget actions took 24.8 sec
Could not install package 'Virgil.SDK 4.3.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:39.6643803
========== Finished ==========

**Comment by amasasi** [comment]
When installing in Xamarin IOS  form version 'Virgil.SDK.3.0.1' 




Attempting to gather dependency information for package 'Virgil.SDK.3.0.1' with respect to project 'MobileApp\MobileDataKit_Collect.iOS', targeting 'Xamarin.iOS,Version=v1.0'
Gathering dependency information took 17.81 sec
Attempting to resolve dependencies for package 'Virgil.SDK.3.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Virgil.SDK.3.0.1'
Resolved actions to install package 'Virgil.SDK.3.0.1'
Retrieving package 'Newtonsoft.Json 8.0.2' from 'nuget.org'.
Retrieving package 'Virgil.Crypto 1.2.2.39' from 'nuget.org'.
Retrieving package 'Virgil.SDK 3.0.1' from 'nuget.org'.
Adding package 'Newtonsoft.Json.8.0.2' to folder 'C:\Projects\DataKit\MobileDataKit\packages'
Added package 'Newtonsoft.Json.8.0.2' to folder 'C:\Projects\DataKit\MobileDataKit\packages'
Added package 'Newtonsoft.Json.8.0.2' to 'packages.config'
Executing script file 'C:\Projects\DataKit\MobileDataKit\packages\Newtonsoft.Json.8.0.2\tools\install.ps1'...
Successfully installed 'Newtonsoft.Json 8.0.2' to MobileDataKit_Collect.iOS
Install failed. Rolling back...
Package 'Virgil.Crypto.1.2.2.39' does not exist in project 'MobileDataKit_Collect.iOS'
Removed package 'Newtonsoft.Json.8.0.2' from 'packages.config'
Package 'Virgil.Crypto.1.2.2.39' does not exist in folder 'C:\Projects\DataKit\MobileDataKit\packages'
Removing package 'Newtonsoft.Json.8.0.2' from folder 'C:\Projects\DataKit\MobileDataKit\packages'
Removed package 'Newtonsoft.Json.8.0.2' from folder 'C:\Projects\DataKit\MobileDataKit\packages'
Executing nuget actions took 1.82 sec
Could not install package 'Virgil.Crypto 1.2.2.39'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:19.6516217
========== Finished ==========

**Comment by unlim-it** [comment]
Hey,

Yeah, thank you for your feedback. We are already working on it.
