### ISSUE TITLE
Got exception when trying to decrypt data with password

### ISSUE THREAD

**Issue by MaxGsomGsom** [VirgilSecurity/virgil-sdk-net#2]
This line

`CryptoHelper.Decrypt(Encoding.UTF8.GetBytes("somedata"), "pass")`

Causes this exception

```
 "System.ApplicationException"
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146232832
    HelpLink: null
    InnerException: null
    Message: "VirgilCipherBase: Recipient with given password not found."
    Source: "Virgil.Crypto"
    StackTrace: "   в Virgil.Crypto.VirgilCipher.DecryptWithPassword(Byte[] encryptedData, Byte[] pwd)\r\n   в Virgil.Crypto.CryptoHelper.Decrypt(Byte[] cipherData, String password)"
    TargetSite: {Byte[] DecryptWithPassword(Byte[], Byte[])}

```

**Comment by unlim-it** [comment]
Hello MaxGsomGsom,

Thanks for your feedback. Unfortunately I can't reproduce your bug on my
side.

Please check this example:
https://github.com/VirgilSecurity/virgil-sdk-net/blob/master/Examples/Virgil.Examples/Crypto/EncryptAndDecryptWithPassword.cs


Best regards
Denis Kurilenko

2016-05-16 11:34 GMT+02:00 MaxGsomGsom <notifications@github.com>:

**Comment by MaxGsomGsom** [comment]
If you encrypt and then decrypt some data with same password, it will work, but if you try to decrypt random data it will raise exception

**Comment by unlim-it** [comment]
The idea is that, you can only decrypt the data you previously encrypted with crypto library, in other case you will got an exception.

**Comment by unlim-it** [comment]
But I got you, in the next release we will fix the exception types.

**Comment by MaxGsomGsom** [comment]
Thanks, I started this topic because I didn't find any documentation about it.
