### ISSUE TITLE
Dependences of virgil_crypto_net.dll

### ISSUE THREAD

**Issue by MaxGsomGsom** [VirgilSecurity/virgil-sdk-net#4]
It seems than virgil_crypto_net.dll have external dependences, because on clear Windows 10 installation this library won't load. May be one of Visual C++ redistributables?

**Comment by SergeySeroshtan** [comment]
> May be one of Visual C++ redistributable?

Exactly :)
[Visual C++ Redistributable for Visual Studio 2015
](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

**Comment by MaxGsomGsom** [comment]
Yes, it works, I think it will be good to specify this in documentation

**Comment by SergeySeroshtan** [comment]
MaxGsomGsom, thanks for your feedback.
This will be included in documentation as soon as possible.
